import "./globals.css";
import type { Metadata } from "next";
import Nav from "@/components/navbar";
import { Providers } from "./providers";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DAWN AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className}]`}>
        
        <Providers>
        <div className="main">
          <div className="gradient" />
        </div>
          <Nav />
          <main className="max-w-[1440px]">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
